image: timbru31/node-alpine-git

before_script:
  - git clone https://github.com/Jonas-Knebel/RedocDemo
  - git checkout main
  - git status
  - git config --global username "Jonas Knebel"
  - git config --global email "jonas.knebel@gmx.com"
  - git config --global password $GIT_SSH

    
pages:

  stage: deploy
  script:
  - npm install -g redoc-cli
  - npm install -g @redocly/openapi-cli
  - for filename in ./*.yaml; 
    do 
        openapi bundle -o ./dist/$filename $filename;
    done
  - git add dist
  - git commit -a -m "Compiled Redoc for YAML Files";
  - git remote add github https://github.com/Jonas-Knebel/RedocDemo.git
  - git config credential.${github}.username "Jonas Knebel"
  - git config credential.${github}.email "jonas.knebel@gmx.com"
  - git status
  - git push github HEAD:main


  artifacts:
    paths:
    - public
  only:
  - main 

