openapi: 3.0.1
info:
  title: FRIDA PensionSerivce
  description: 
    $ref: './docs/FRIDA_PensionInformation_OA3/description_en.md'
  termsOfService: 'https://github.com/FRIDA-official'
  contact:
    email: anton.rott@accenture.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.0.1
externalDocs:
  description: Hier folgt noch ein Verweis auf die externe Doku
  url: 'http://swagger.io' 

servers:
  - url: 'https://test-api-impl-backend-jaxrs.herokuapp.com/v2'

paths:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/paths'
components:
  $ref: './docs/FRIDA_PensionInformation_OA3/FRIDA_PensionInformation_OA3_full_en.yaml#/components'

    