name: start
on: [push]
jobs:
    build:
        runs-on: ubuntu-20.04
        container: 
            image: jonasknebel/resolver_for_yaml_dependencies:latest     
        steps:
        - uses: actions/checkout@master
          with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo   
        - name: Create local changes
          run: for filename in ./*.yaml; do redoc-cli bundle -o ./dist/${filename:2:$((${#filename})) - 7}.html $filename; done        
        - name: Add Files
          run: git add dist/*
        - name: Commit files
          run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "Add changes" -a --allow-empty
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}   
         
    repo-sync:
        runs-on: ubuntu-latest
        steps:
          - name: repo-sync
            uses: wei/git-sync@v3
            with:
              source_repo: "username/repository"
              source_branch: "main"
              destination_repo: "git@github.com:org/repository.git"
              destination_branch: "main"
              ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
              source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
              destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
         