name: start
on: [push]
jobs:
    SolveDeps:
        runs-on: ubuntu-latest
        container: jonasknebel/resolver_for_yaml_dependencies:latest
        steps:
            - uses: actions/checkout@v2
            - run: for filename in ./*.yml; do openapi bundle -o ./dist/$filename $filename; done
