name: start
on: [push]
jobs:
    SolveDeps:
        runs-on: ubuntu-latest
        container: jonasknebel/resolver_for_yaml_dependencies:latest
        steps:
            steps:
              - name: Read package.json
                id: package
                uses: juliangruber/read-file-action@v1
                with:
                  path: ./package.json
              - name: Echo package.json
     