name: start
on: [push]
jobs:
    SolveDeps:
        runs-on: ubuntu-latest
        container: jonasknebel/resolver_for_yaml_dependencies:latest
        steps:
            - name: check yaml files
              uses: ./*.yml
            - run: for filename in *.yaml; do openapi bundle -o ./dist/$filename $filename; done
