name: start
on: [push]
jobs:
    SolveDeps:
        runs-on: ubuntu-latest
        container: jonasknebel/resolver_for_yaml_dependencies:latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                path: main
           
     