name: start
on: [push]
jobs:
    SolveDeps:
        runs-on: ubuntu-latest
        container: jonasknebel/resolver_for_yaml_dependencies:latest
        steps:
          - name: Checkout
            uses: action/chechkout@v2
            run: ls
           
     